set nocompatible              " Use Vim defaults, not vi
set background=dark           " Use colors suitable for dark background
syntax on                     " Enable syntax highlighting
set number                    " Show line numbers
set relativenumber            " Show relative line numbers
set cursorline                " Highlight current line
set tabstop=4                 " Number of spaces a <Tab> in the file counts for
set shiftwidth=4              " Number of spaces to use for each step of (auto)indent
set expandtab                 " Use spaces instead of tabs
set smartindent               " Smart autoindenting on new lines
set showmatch                 " Highlight matching parenthesis
set incsearch                 " Show search matches as you type
set ignorecase smartcase      " Case-insensitive search unless uppercase used
set mouse=a                   " Enable mouse support
set clipboard=unnamedplus     " Use system clipboard
set scrolloff=5               " Keep 5 lines visible when scrolling

colorscheme desert            " Or any other dark colorscheme you have

" Better splits navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Use space as leader key
let mapleader=" "

" Quick save
nnoremap <leader>w :w<CR>
