# Hyprpaper configuration

# Preload wallpapers
preload = ~/Pictures/wallpapers/Abstract-Nature.jpg
preload = ~/Pictures/wallpapers/Backyard.png
preload = ~/Pictures/wallpapers/Candle-Photo.png
preload = ~/Pictures/wallpapers/Concept-Japanese house.png
preload = ~/Pictures/wallpapers/Courtside-Sunset.png
preload = ~/Pictures/wallpapers/Dark_Nature.png
preload = ~/Pictures/wallpapers/Fantasy-Garden.png
preload = ~/Pictures/wallpapers/Fantasy-Lake1.png
preload = ~/Pictures/wallpapers/Fantasy-Landscape1.png
preload = ~/Pictures/wallpapers/Fantasy-Landscape3.png
preload = ~/Pictures/wallpapers/Lofi_Cat.png
preload = ~/Pictures/wallpapers/Nature-Flower.png
preload = ~/Pictures/wallpapers/Pastel-Window.png
preload = ~/Pictures/wallpapers/Street-2.png
preload = ~/Pictures/wallpapers/Sunset-Forrest.png
preload = ~/Pictures/wallpapers/Sunset-room.png

# Default wallpaper for all monitors (overridden at runtime by wallpaper.sh)
wallpaper = ,~/Pictures/wallpapers/Dark_Nature.png
splash = false
