-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
        hide_on_tablet = true,
    },
    decoration = {
        blur = {
            enabled = false,
        },
        inactive_opacity = 1.0,
        rounding = 0,
        shadow = {
            enabled = false,
        },
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        border_size = 2,
        gaps_in = 2,
        gaps_out = 2,
        layout = "dwindle",
        snap = {
            enabled = false,
        },
    },
})
