env = XCURSOR_SIZE, 24
env = HYPRCURSOR_SIZE, 24
env = QT_QPA_PLATFORMTHEME,qt6ct

exec-once = bash ~/.config/scripts/restart.sh
exec-once = hyprshell run
exec-once = bash ~/.config/scripts/immich-sync.sh
exec-once = bash ~/.config/scripts/jellyfin-music-sync.sh --daemon
