-- General compositor settings.

-- Pull wallpaper-driven accent colors. modules/colors.lua is generated by
-- scripts/accent-from-wallpaper.py; fall back to sensible defaults so a
-- fresh install boots cleanly before the first wallpaper change.
local ok, colors = pcall(require, "modules.colors")
if not ok then
    colors = { accent = "rgba(3b82f6ee)", accentSoft = "rgba(1e3a8aee)" }
end

hl.config({
    general = {
        gaps_in     = 4,
        gaps_out    = 4,
        border_size = 4,
        col = {
            active_border   = colors.accent,
            inactive_border = colors.accentSoft,
        },
        allow_tearing    = true,
        resize_on_border = true,
        layout           = "dwindle",
    },
    misc = {
        force_default_wallpaper   = -1,
        disable_hyprland_logo     = true,
        disable_autoreload        = false,
        mouse_move_enables_dpms   = true,
        key_press_enables_dpms    = true,
        always_follow_on_dnd      = true,
        layers_hog_keyboard_focus = true,
        animate_manual_resizes    = false,
        disable_splash_rendering  = true,
        focus_on_activate         = false,
        -- Variable refresh rate. 2 = fullscreen-only so the desktop
        -- stays at the monitor's native rate; G-Sync/FreeSync kicks
        -- in only inside games.
        vrr                       = 2,
    },
    cursor = {
        no_hardware_cursors = false,
    },
    dwindle = {
        preserve_split = true,
    },
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles   = true,
    },
})
