#!/usr/bin/env python3
"""Derive Material You colors from a wallpaper and write the config files
that Hyprland and Quickshell consume.

Uses Google's material-color-utilities algorithm (via the materialyoucolor
PyPI package): Wu/CELEBI quantization → HCT-based seed scoring → Tonal Spot
scheme. Result is a small slice of the Material 3 dark scheme — primary,
primaryContainer, the matching `on*` foregrounds, and outline.

Outputs:
  ~/.config/hypr/modules/colors.conf  -> $accent / $accentSoft (rgba)
  ~/.cache/quickshell/accent.conf     -> primary= / soft= / onPrimary= ...
"""

import os
import sys
from pathlib import Path

from PIL import Image
from materialyoucolor.quantize import QuantizeCelebi
from materialyoucolor.score.score import Score
from materialyoucolor.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot
from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors

HOME = Path(os.environ["HOME"])
HYPR_OUT = HOME / ".config/hypr/modules/colors.conf"
QS_OUT   = HOME / ".cache/quickshell/accent.conf"

# Material 3 roles we expose to the rest of the system. Internal names
# match the M3 spec for clarity; on the QML side `onPrimary` and friends
# are renamed to `fgPrimary` because QML treats identifiers starting with
# `on` as signal handlers (see Theme.qml).
ROLES = [
    "primary",            # main accent (e.g. button bg, focus ring)
    "onPrimary",          # -> fgPrimary in Theme.qml: text/icon over primary
    "primaryContainer",   # softer accent surface (inactive border, chip bg)
    "onPrimaryContainer", # -> fgPrimaryContainer in Theme.qml
    "outline",            # accent-tinted divider
]
# QML can't have property names beginning with `on` — rewrite on output.
QML_KEY = {
    "onPrimary":          "fgPrimary",
    "onPrimaryContainer": "fgPrimaryContainer",
}


def hex_from_argb(c: int) -> str:
    return "#{:02x}{:02x}{:02x}".format((c >> 16) & 0xff, (c >> 8) & 0xff, c & 0xff)


def extract_scheme(path: str) -> dict:
    img = Image.open(path).convert("RGB")
    img.thumbnail((128, 128))
    quantized = QuantizeCelebi(list(img.getdata()), 128)
    seed = Score.score(quantized)[0]
    scheme = SchemeTonalSpot(Hct.from_int(seed), True, 0.0)
    return {r: hex_from_argb(getattr(MaterialDynamicColors, r).get_hct(scheme).to_int())
            for r in ROLES}


def main() -> None:
    if len(sys.argv) < 2:
        print("usage: accent-from-wallpaper.py <wallpaper>", file=sys.stderr)
        sys.exit(1)
    wp = sys.argv[1]

    try:
        colors = extract_scheme(wp)
    except Exception as e:
        print(f"accent extraction failed: {e}", file=sys.stderr)
        sys.exit(1)

    HYPR_OUT.parent.mkdir(parents=True, exist_ok=True)
    QS_OUT.parent.mkdir(parents=True, exist_ok=True)

    # Hyprland: variables sourced by hyprland.conf. Soft uses primaryContainer
    # since that's the Material-correct "softer surface tinted like the accent".
    HYPR_OUT.write_text(
        f"# Generated by accent-from-wallpaper.py — do not edit by hand.\n"
        f"$accent     = rgba({colors['primary'][1:]}ee)\n"
        f"$accentSoft = rgba({colors['primaryContainer'][1:]}ee)\n"
    )

    # Quickshell: watched by Theme.qml's FileView. Apply QML_KEY rename.
    QS_OUT.write_text(
        "\n".join(f"{QML_KEY.get(r, r)}={colors[r]}" for r in ROLES) + "\n"
    )

    print("accent:", " ".join(f"{r}={colors[r]}" for r in ROLES))


if __name__ == "__main__":
    main()
